name: GitHub Pipeline

on:
  push:
    branches: ci-cd implem
  pull_request:
    branches: ci-cd implem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show installed packages (optional) # Show packages for debugging
        run: pip freeze
  unit_and_api_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run API Tests 
        run: pytest tests/api/ 

    
